// Code generated by scripts/gen_api_routes.py from docs/api/openapi.yaml.
// DO NOT EDIT BY HAND — regenerate with `make api-gen` after changing the
// spec. The management API registers and validates every route against
// this table (contract testing, p6.api-impl).

package api

// specRoutes is the compiled route table of the OpenAPI contract. Every
// entry must have a handler registered under the same OperationID; the
// conformance test asserts set equality and auth behavior.
var specRoutes = []routeSpec{
	{Method: "POST", Path: "/api/auth/login", OperationID: "login", Auth: "public", RateLimit: "auth"},
	{Method: "POST", Path: "/api/auth/logout", OperationID: "logout", Auth: "admin-session", RateLimit: "write"},
	{Method: "GET", Path: "/api/auth/session", OperationID: "getSession", Auth: "admin-session", RateLimit: "read"},
	{Method: "POST", Path: "/api/auth/setup", OperationID: "createAdmin", Auth: "public", RateLimit: "auth"},
	{Method: "GET", Path: "/api/auth/setup-status", OperationID: "getSetupStatus", Auth: "public", RateLimit: "auth"},
	{Method: "GET", Path: "/api/keys", OperationID: "listKeys", Auth: "admin-session", RateLimit: "read"},
	{Method: "POST", Path: "/api/keys", OperationID: "createKey", Auth: "admin-session", RateLimit: "write"},
	{Method: "DELETE", Path: "/api/keys/{id}", OperationID: "deleteKey", Auth: "admin-session", RateLimit: "write"},
	{Method: "GET", Path: "/api/keys/{id}", OperationID: "getKey", Auth: "admin-session", RateLimit: "read"},
	{Method: "PATCH", Path: "/api/keys/{id}", OperationID: "updateKey", Auth: "admin-session", RateLimit: "write"},
	{Method: "POST", Path: "/api/keys/{id}/revoke", OperationID: "revokeKey", Auth: "admin-session", RateLimit: "write"},
	{Method: "GET", Path: "/api/keys/{id}/usage", OperationID: "getKeyUsage", Auth: "admin-session", RateLimit: "read"},
	{Method: "GET", Path: "/api/logs/live", OperationID: "streamLiveLogs", Auth: "admin-session", RateLimit: "stream"},
	{Method: "GET", Path: "/api/logs/recent", OperationID: "recentLogs", Auth: "admin-session", RateLimit: "read"},
	{Method: "GET", Path: "/api/models", OperationID: "listModels", Auth: "admin-session", RateLimit: "read"},
	{Method: "POST", Path: "/api/models", OperationID: "createModel", Auth: "admin-session", RateLimit: "write"},
	{Method: "DELETE", Path: "/api/models/{id}", OperationID: "deleteModel", Auth: "admin-session", RateLimit: "write"},
	{Method: "GET", Path: "/api/models/{id}", OperationID: "getModel", Auth: "admin-session", RateLimit: "read"},
	{Method: "PUT", Path: "/api/models/{id}", OperationID: "replaceModel", Auth: "admin-session", RateLimit: "write"},
	{Method: "GET", Path: "/api/providers", OperationID: "listProviders", Auth: "admin-session", RateLimit: "read"},
	{Method: "POST", Path: "/api/providers", OperationID: "createProvider", Auth: "admin-session", RateLimit: "write"},
	{Method: "DELETE", Path: "/api/providers/{id}", OperationID: "deleteProvider", Auth: "admin-session", RateLimit: "write"},
	{Method: "GET", Path: "/api/providers/{id}", OperationID: "getProvider", Auth: "admin-session", RateLimit: "read"},
	{Method: "PATCH", Path: "/api/providers/{id}", OperationID: "updateProvider", Auth: "admin-session", RateLimit: "write"},
	{Method: "POST", Path: "/api/providers/{id}/test", OperationID: "testProvider", Auth: "admin-session", RateLimit: "probe"},
	{Method: "GET", Path: "/api/requests", OperationID: "listRequests", Auth: "admin-session", RateLimit: "read"},
	{Method: "GET", Path: "/api/routing-rules", OperationID: "listRoutingRules", Auth: "admin-session", RateLimit: "read"},
	{Method: "POST", Path: "/api/routing-rules", OperationID: "createRoutingRule", Auth: "admin-session", RateLimit: "write"},
	{Method: "DELETE", Path: "/api/routing-rules/{id}", OperationID: "deleteRoutingRule", Auth: "admin-session", RateLimit: "write"},
	{Method: "PUT", Path: "/api/routing-rules/{id}", OperationID: "replaceRoutingRule", Auth: "admin-session", RateLimit: "write"},
	{Method: "GET", Path: "/api/routing/health", OperationID: "getRoutingHealth", Auth: "admin-session", RateLimit: "read"},
	{Method: "GET", Path: "/api/system/config", OperationID: "getEffectiveConfig", Auth: "admin-session", RateLimit: "read"},
	{Method: "GET", Path: "/api/system/status", OperationID: "getSystemStatus", Auth: "admin-session", RateLimit: "read"},
	{Method: "GET", Path: "/api/usage/range", OperationID: "queryUsageRange", Auth: "admin-session", RateLimit: "read"},
	{Method: "GET", Path: "/api/usage/summary", OperationID: "queryUsageSummary", Auth: "admin-session", RateLimit: "read"},
}
