// Code generated by scripts/gen_api_client.py from docs/api/openapi.yaml.
// DO NOT EDIT BY HAND — regenerate with `make api-gen`.

import type * as T from "./types"

/**
 * Error shape from the management API: the wire envelope's
 * `error` object, raised as an exception.
 */
export class ApiError extends Error {
  status: number
  type: string
  code?: string
  param?: string
  retryable: boolean

  constructor(fields: {
    status: number
    type: string
    code?: string
    param?: string
    retryable: boolean
    message: string
  }) {
    super(fields.message)
    this.name = "ApiError"
    this.status = fields.status
    this.type = fields.type
    this.code = fields.code
    this.param = fields.param
    this.retryable = fields.retryable
  }
}

export interface ClientOptions {
  /** Base URL; empty means same-origin. */
  baseUrl?: string
  /** CSRF token for mutating calls (from GET /api/auth/session). */
  csrfToken?: string
  /** Custom fetch (tests). */
  fetchFn?: typeof fetch
}

const MUTATING = new Set(["POST", "PUT", "PATCH", "DELETE"])

export class OneGateClient {
  private baseUrl: string
  private csrfToken: string
  private fetchFn: typeof fetch

  constructor(opts: ClientOptions = {}) {
    this.baseUrl = opts.baseUrl ?? ""
    this.csrfToken = opts.csrfToken ?? ""
    this.fetchFn = opts.fetchFn ?? fetch.bind(globalThis)
  }

  setCsrfToken(token: string) {
    this.csrfToken = token
  }

  private async request<R>(
    method: string,
    path: string,
    init: { query?: Record<string, string | number | undefined>; body?: unknown } = {}
  ): Promise<R> {
    const url = new URL(this.baseUrl + path, globalThis.location?.origin ?? "http://localhost")
    for (const [k, v] of Object.entries(init.query ?? {})) {
      if (v !== undefined) url.searchParams.set(k, String(v))
    }
    const headers: Record<string, string> = {}
    if (init.body !== undefined) headers["Content-Type"] = "application/json"
    if (MUTATING.has(method) && this.csrfToken) headers["X-CSRF-Token"] = this.csrfToken
    const res = await this.fetchFn(url.toString(), {
      method,
      headers,
      credentials: "same-origin",
      body: init.body === undefined ? undefined : JSON.stringify(init.body),
    })
    if (res.status === 204) return undefined as R
    const payload = await res.json().catch(() => null)
    if (!res.ok) {
      const e = (payload as { error?: Record<string, unknown> } | null)?.error
      throw new ApiError({
        status: res.status,
        type: (e?.type as string) ?? "api_error",
        code: e?.code as string | undefined,
        param: e?.param as string | undefined,
        retryable: (e?.retryable as boolean | undefined) ?? false,
        message: (e?.message as string | undefined) ?? res.statusText,
      })
    }
    return payload as R
  }

  /** Create the admin account (first run only) (POST /api/auth/setup) */
  createAdmin(body: {
  username: T.Username
  password: T.Password
}): Promise<T.CreateAdminResponse> {
    return this.request<T.CreateAdminResponse>("POST", `/api/auth/setup`, { body })
  }

  /** Mint a virtual key (POST /api/keys) */
  createKey(body: {
  name: T.KeyName
  scopes?: T.KeyScopes
  limits?: T.KeyLimits
  expires_at_ms?: number
}): Promise<T.CreateKeyResponse> {
    return this.request<T.CreateKeyResponse>("POST", `/api/keys`, { body })
  }

  /** Register a canonical model (POST /api/models) */
  createModel(body: T.ModelInput): Promise<T.CreateModelResponse> {
    return this.request<T.CreateModelResponse>("POST", `/api/models`, { body })
  }

  /** Register a provider (POST /api/providers) */
  createProvider(body: T.ProviderCreate): Promise<T.CreateProviderResponse> {
    return this.request<T.CreateProviderResponse>("POST", `/api/providers`, { body })
  }

  /** Create a routing rule (POST /api/routing-rules) */
  createRoutingRule(body: T.RoutingRuleInput): Promise<T.CreateRoutingRuleResponse> {
    return this.request<T.CreateRoutingRuleResponse>("POST", `/api/routing-rules`, { body })
  }

  /** Permanently delete a virtual key (DELETE /api/keys/{id}) */
  deleteKey(id: string): Promise<T.DeleteKeyResponse> {
    return this.request<T.DeleteKeyResponse>("DELETE", `/api/keys/${id}`)
  }

  /** Remove a canonical model (DELETE /api/models/{id}) */
  deleteModel(id: string): Promise<T.DeleteModelResponse> {
    return this.request<T.DeleteModelResponse>("DELETE", `/api/models/${id}`)
  }

  /** Remove a provider (DELETE /api/providers/{id}) */
  deleteProvider(id: string): Promise<T.DeleteProviderResponse> {
    return this.request<T.DeleteProviderResponse>("DELETE", `/api/providers/${id}`)
  }

  /** Remove a routing rule (DELETE /api/routing-rules/{id}) */
  deleteRoutingRule(id: string): Promise<T.DeleteRoutingRuleResponse> {
    return this.request<T.DeleteRoutingRuleResponse>("DELETE", `/api/routing-rules/${id}`)
  }

  /** Read-only effective runtime configuration (GET /api/system/config) */
  getEffectiveConfig(): Promise<T.GetEffectiveConfigResponse> {
    return this.request<T.GetEffectiveConfigResponse>("GET", `/api/system/config`)
  }

  /** Fetch one virtual key (GET /api/keys/{id}) */
  getKey(id: string): Promise<T.GetKeyResponse> {
    return this.request<T.GetKeyResponse>("GET", `/api/keys/${id}`)
  }

  /** Usage totals for one key over a time window (GET /api/keys/{id}/usage) */
  getKeyUsage(id: string, params?: T.GetKeyUsageParams): Promise<T.GetKeyUsageResponse> {
    return this.request<T.GetKeyUsageResponse>("GET", `/api/keys/${id}/usage`, { query: { "start_ms": params?.start_ms, "end_ms": params?.end_ms } })
  }

  /** Fetch one canonical model (GET /api/models/{id}) */
  getModel(id: string): Promise<T.GetModelResponse> {
    return this.request<T.GetModelResponse>("GET", `/api/models/${id}`)
  }

  /** Fetch one provider (GET /api/providers/{id}) */
  getProvider(id: string): Promise<T.GetProviderResponse> {
    return this.request<T.GetProviderResponse>("GET", `/api/providers/${id}`)
  }

  /** Target circuit states and recent transition events (GET /api/routing/health) */
  getRoutingHealth(params?: T.GetRoutingHealthParams): Promise<T.GetRoutingHealthResponse> {
    return this.request<T.GetRoutingHealthResponse>("GET", `/api/routing/health`, { query: { "event_limit": params?.event_limit } })
  }

  /** Describe the current session (GET /api/auth/session) */
  getSession(): Promise<T.GetSessionResponse> {
    return this.request<T.GetSessionResponse>("GET", `/api/auth/session`)
  }

  /** Report whether first-run admin setup is required (GET /api/auth/setup-status) */
  getSetupStatus(): Promise<T.GetSetupStatusResponse> {
    return this.request<T.GetSetupStatusResponse>("GET", `/api/auth/setup-status`)
  }

  /** Gateway status card (version, uptime, object counts) (GET /api/system/status) */
  getSystemStatus(): Promise<T.GetSystemStatusResponse> {
    return this.request<T.GetSystemStatusResponse>("GET", `/api/system/status`)
  }

  /** List virtual keys (GET /api/keys) */
  listKeys(params?: T.ListKeysParams): Promise<T.ListKeysResponse> {
    return this.request<T.ListKeysResponse>("GET", `/api/keys`, { query: { "limit": params?.limit, "cursor": params?.cursor } })
  }

  /** List canonical models with their targets (GET /api/models) */
  listModels(params?: T.ListModelsParams): Promise<T.ListModelsResponse> {
    return this.request<T.ListModelsResponse>("GET", `/api/models`, { query: { "limit": params?.limit, "cursor": params?.cursor } })
  }

  /** List configured providers (GET /api/providers) */
  listProviders(params?: T.ListProvidersParams): Promise<T.ListProvidersResponse> {
    return this.request<T.ListProvidersResponse>("GET", `/api/providers`, { query: { "limit": params?.limit, "cursor": params?.cursor } })
  }

  /** Raw request records, newest first (GET /api/requests) */
  listRequests(params?: T.ListRequestsParams): Promise<T.ListRequestsResponse> {
    return this.request<T.ListRequestsResponse>("GET", `/api/requests`, { query: { "limit": params?.limit, "cursor": params?.cursor, "vkey_id": params?.vkey_id } })
  }

  /** List routing rules (GET /api/routing-rules) */
  listRoutingRules(params?: T.ListRoutingRulesParams): Promise<T.ListRoutingRulesResponse> {
    return this.request<T.ListRoutingRulesResponse>("GET", `/api/routing-rules`, { query: { "limit": params?.limit, "cursor": params?.cursor } })
  }

  /** Log in with username and password (POST /api/auth/login) */
  login(body: {
  username: T.Username
  password: T.Password
}): Promise<T.LoginResponse> {
    return this.request<T.LoginResponse>("POST", `/api/auth/login`, { body })
  }

  /** Terminate the current session (POST /api/auth/logout) */
  logout(): Promise<T.LogoutResponse> {
    return this.request<T.LogoutResponse>("POST", `/api/auth/logout`)
  }

  /** Time-series usage buckets for a window (GET /api/usage/range) */
  queryUsageRange(params?: T.QueryUsageRangeParams): Promise<T.QueryUsageRangeResponse> {
    return this.request<T.QueryUsageRangeResponse>("GET", `/api/usage/range`, { query: { "start_ms": params?.start_ms, "end_ms": params?.end_ms, "step": params?.step, "vkey_id": params?.vkey_id, "model_id": params?.model_id, "provider_id": params?.provider_id } })
  }

  /** Usage totals for a window (GET /api/usage/summary) */
  queryUsageSummary(params?: T.QueryUsageSummaryParams): Promise<T.QueryUsageSummaryResponse> {
    return this.request<T.QueryUsageSummaryResponse>("GET", `/api/usage/summary`, { query: { "start_ms": params?.start_ms, "end_ms": params?.end_ms, "vkey_id": params?.vkey_id, "model_id": params?.model_id, "provider_id": params?.provider_id } })
  }

  /** Snapshot of the recent-log ring buffer (GET /api/logs/recent) */
  recentLogs(params?: T.RecentLogsParams): Promise<T.RecentLogsResponse> {
    return this.request<T.RecentLogsResponse>("GET", `/api/logs/recent`, { query: { "limit": params?.limit, "min_level": params?.min_level, "trace_id": params?.trace_id, "provider": params?.provider } })
  }

  /** Replace a model and its fallback chain (PUT /api/models/{id}) */
  replaceModel(id: string, body: T.ModelInput): Promise<T.ReplaceModelResponse> {
    return this.request<T.ReplaceModelResponse>("PUT", `/api/models/${id}`, { body })
  }

  /** Replace a routing rule (PUT /api/routing-rules/{id}) */
  replaceRoutingRule(id: string, body: T.RoutingRuleInput): Promise<T.ReplaceRoutingRuleResponse> {
    return this.request<T.ReplaceRoutingRuleResponse>("PUT", `/api/routing-rules/${id}`, { body })
  }

  /** Revoke a virtual key (POST /api/keys/{id}/revoke) */
  revokeKey(id: string): Promise<T.RevokeKeyResponse> {
    return this.request<T.RevokeKeyResponse>("POST", `/api/keys/${id}/revoke`)
  }

  /** Live log stream (Server-Sent Events) (GET /api/logs/live) */
  streamLiveLogs(params?: T.StreamLiveLogsParams): Promise<T.StreamLiveLogsResponse> {
    return this.request<T.StreamLiveLogsResponse>("GET", `/api/logs/live`, { query: { "min_level": params?.min_level, "trace_id": params?.trace_id, "provider": params?.provider } })
  }

  /** Test the provider connection (POST /api/providers/{id}/test) */
  testProvider(id: string): Promise<T.TestProviderResponse> {
    return this.request<T.TestProviderResponse>("POST", `/api/providers/${id}/test`)
  }

  /** Update key metadata, scopes, or limits (PATCH /api/keys/{id}) */
  updateKey(id: string, body: {
  name?: T.KeyName
  scopes?: T.KeyScopes
  limits?: T.KeyLimits
  expires_at_ms?: number
}): Promise<T.UpdateKeyResponse> {
    return this.request<T.UpdateKeyResponse>("PATCH", `/api/keys/${id}`, { body })
  }

  /** Update provider fields (PATCH /api/providers/{id}) */
  updateProvider(id: string, body: T.ProviderUpdate): Promise<T.UpdateProviderResponse> {
    return this.request<T.UpdateProviderResponse>("PATCH", `/api/providers/${id}`, { body })
  }
}
