// Code generated by scripts/gen_api_client.py from docs/api/openapi.yaml.
// DO NOT EDIT BY HAND — regenerate with `make api-gen`.

// ---------------------------------------------------------------------
// Component schemas
// ---------------------------------------------------------------------
export type ID = string

export type UnixMS = number

export type MicroUSD = number

export type Username = string

export type Password = string

export type KeyName = string

export interface PageMeta {
  items: unknown
  next_cursor: (string | null)
}

export interface ErrorEnvelope {
  error: {
    status: number
    type: "invalid_request_error" | "authentication_error" | "permission_error" | "not_found_error" | "request_too_large" | "rate_limit_error" | "overloaded_error" | "api_error" | "timeout_error" | "cancelled_error" | "internal_error"
    code?: string
    message: string
    param?: string
    retryable: boolean
  }
}

export interface SessionInfo {
  user: {
    username: Username
  }
  csrf_token: string
  expires_at_ms: number
}

export interface Provider {
  id: ID
  name: string
  protocol: "openai" | "anthropic" | "gemini" | "openai-compat"
  base_url: string
  masked_key?: (string | null)
  enabled: boolean
  created_ms: UnixMS
  updated_ms: UnixMS
}

export interface ProviderCreate {
  id?: ID
  name: string
  protocol: "openai" | "anthropic" | "gemini" | "openai-compat"
  base_url: string
  api_key?: (string | null)
  enabled?: boolean
}

export interface ProviderUpdate {
  name?: string
  base_url?: string
  api_key?: (string | null)
  enabled?: boolean
}

export interface ProviderTestResult {
  ok: boolean
  latency_ms: number
  error?: ErrorEnvelope & unknown
}

export interface ModelCapabilities {
  tools?: boolean
  vision?: boolean
  json_mode?: boolean
  stream?: boolean
}

export interface ModelTarget {
  provider_id: ID
  provider_model: string
  weight?: number
  position?: number
  cost_multiplier?: number
  capabilities?: ModelCapabilities & unknown
}

export interface Model {
  id: string
  aliases?: Array<string>
  targets: Array<ModelTarget>
  capabilities: ModelCapabilities
  created_ms: UnixMS
  updated_ms: UnixMS
}

export interface ModelInput {
  id: string
  aliases?: Array<string>
  targets: Array<ModelTarget>
  capabilities?: ModelCapabilities
}

export interface RoutingRule {
  id: ID
  model_id: string
  policy: "ordered" | "weighted" | "cost" | "latency"
  enabled: boolean
  position: number
}

export interface RoutingRuleInput {
  id?: ID
  model_id: string
  policy: "ordered" | "weighted" | "cost" | "latency"
  enabled?: boolean
  position?: number
}

export interface TargetHealth {
  provider_id: ID
  model: string
  state: "closed" | "open" | "half_open"
  consecutive_failures?: number
  cooldown_until_ms?: (number | null)
}

export interface HealthEvent {
  timestamp_ms: UnixMS
  provider_id: ID
  model: string
  old_state: "closed" | "open" | "half_open"
  new_state: "closed" | "open" | "half_open"
  reason: string
  consecutive_failures?: number
}

export interface KeyScopes {
  allowed_models?: Array<string>
  allowed_providers?: Array<ID>
  policy_override?: "ordered" | "weighted" | "cost" | "latency"
  model_overrides?: Record<string, "ordered" | "weighted" | "cost" | "latency">
}

export interface KeyLimits {
  rpm?: number
  tpm?: number
  concurrency?: number
  max_spend_usd_micros?: number
}

export interface VirtualKey {
  id: ID
  name: string
  prefix: string
  scopes: KeyScopes
  limits: KeyLimits
  status: "active" | "revoked"
  created_ms: UnixMS
  expires_ms?: (number | null)
  last_used_ms?: (number | null)
}

export interface UsageBucket {
  bucket_start_ms: UnixMS
  virtual_key_id?: (string | null)
  model_id?: (string | null)
  provider_id?: (string | null)
  requests: number
  errors: number
  prompt_tokens: number
  completion_tokens: number
  total_tokens: number
  cost_usd_micros: MicroUSD
}

export interface UsageTotals {
  requests: number
  errors: number
  prompt_tokens: number
  completion_tokens: number
  total_tokens: number
  cost_usd_micros: MicroUSD
}

export interface RequestRecord {
  id: string
  trace_id: string
  virtual_key_id?: (string | null)
  model_requested?: string
  model_served?: (string | null)
  provider_id?: (string | null)
  status: "success" | "error" | "cancelled"
  error_code?: (string | null)
  stream: boolean
  prompt_tokens?: number
  completion_tokens?: number
  total_tokens?: number
  cost_usd_micros?: MicroUSD
  latency_ms?: number
  ttft_ms?: (number | null)
  attempts?: number
  created_ms: UnixMS
}

export interface LogEntry {
  timestamp: string
  level: "debug" | "info" | "warn" | "error"
  message: string
  trace_id?: string
  provider?: string
  attrs?: Record<string, unknown>
}

export interface SystemStatus {
  version: string
  git_commit?: string
  schema_version: number
  uptime_ms: number
  counts: {
    providers: number
    models: number
    keys: number
    requests: number
  }
  storage?: {
    db_size_bytes?: number
  }
}

export interface SystemConfig {
  host: string
  port: number
  data_dir: string
  log_level: "debug" | "info" | "warn" | "error"
  http: {
    read_header_timeout_ms: number
    read_timeout_ms: number
    write_timeout_ms: number
    idle_timeout_ms: number
  }
  reload: {
    enabled: boolean
    poll_ms: number
  }
}

// ---------------------------------------------------------------------
// Operation types (responses, query params)
// ---------------------------------------------------------------------
export type CreateAdminResponse = SessionInfo

export type CreateKeyResponse = {
  key: VirtualKey
  raw_key: string
}

export type CreateModelResponse = Model

export type CreateProviderResponse = Provider

export type CreateRoutingRuleResponse = RoutingRule

export type DeleteKeyResponse = void

export type DeleteModelResponse = void

export type DeleteProviderResponse = void

export type DeleteRoutingRuleResponse = void

export type GetEffectiveConfigResponse = SystemConfig

export type GetKeyResponse = VirtualKey

export type GetKeyUsageResponse = UsageTotals
export interface GetKeyUsageParams {
  start_ms?: number
  end_ms?: number
}

export type GetModelResponse = Model

export type GetProviderResponse = Provider

export type GetRoutingHealthResponse = {
  targets: Array<TargetHealth>
  events: Array<HealthEvent>
}
export interface GetRoutingHealthParams {
  event_limit?: number
}

export type GetSessionResponse = SessionInfo

export type GetSetupStatusResponse = {
  setup_required: boolean
}

export type GetSystemStatusResponse = SystemStatus

export type ListKeysResponse = PageMeta & {
  items: Array<VirtualKey>
}
export interface ListKeysParams {
  limit?: number
  cursor?: string
}

export type ListModelsResponse = PageMeta & {
  items: Array<Model>
}
export interface ListModelsParams {
  limit?: number
  cursor?: string
}

export type ListProvidersResponse = PageMeta & {
  items: Array<Provider>
}
export interface ListProvidersParams {
  limit?: number
  cursor?: string
}

export type ListRequestsResponse = PageMeta & {
  items: Array<RequestRecord>
}
export interface ListRequestsParams {
  limit?: number
  cursor?: string
  vkey_id?: ID
}

export type ListRoutingRulesResponse = PageMeta & {
  items: Array<RoutingRule>
}
export interface ListRoutingRulesParams {
  limit?: number
  cursor?: string
}

export type LoginResponse = SessionInfo

export type LogoutResponse = void

export type QueryUsageRangeResponse = {
  buckets: Array<UsageBucket>
}
export interface QueryUsageRangeParams {
  start_ms?: number
  end_ms?: number
  step?: "hour" | "day"
  vkey_id?: ID
  model_id?: string
  provider_id?: ID
}

export type QueryUsageSummaryResponse = UsageTotals
export interface QueryUsageSummaryParams {
  start_ms?: number
  end_ms?: number
  vkey_id?: ID
  model_id?: string
  provider_id?: ID
}

export type RecentLogsResponse = {
  entries: Array<LogEntry>
}
export interface RecentLogsParams {
  limit?: number
  min_level?: "debug" | "info" | "warn" | "error"
  trace_id?: string
  provider?: string
}

export type ReplaceModelResponse = Model

export type ReplaceRoutingRuleResponse = RoutingRule

export type RevokeKeyResponse = VirtualKey

export type StreamLiveLogsResponse = void
export interface StreamLiveLogsParams {
  min_level?: "debug" | "info" | "warn" | "error"
  trace_id?: string
  provider?: string
}

export type TestProviderResponse = ProviderTestResult

export type UpdateKeyResponse = VirtualKey

export type UpdateProviderResponse = Provider

