#!/usr/bin/env python3
"""Generate internal/api/spec_gen.go from docs/api/openapi.yaml.

The management API's route table is GENERATED from the OpenAPI contract so
that handler registration and the conformance tests always run against the
spec (p6.api-impl acceptance: "Handler conformance tests run against the
spec"). Drift is impossible: regenerating after a spec change either
updates the table or fails compilation (a handler for a removed operation
no longer exists).

Usage:
    python3 scripts/gen_api_routes.py            # write internal/api/spec_gen.go
    python3 scripts/gen_api_routes.py --check    # exit 1 when stale (CI)

Requires: PyYAML (already used by scripts/graph_status.py tooling env).
"""
import subprocess
import sys

import yaml

SPEC = "docs/api/openapi.yaml"
OUT = "internal/api/spec_gen.go"

HEADER = """// Code generated by scripts/gen_api_routes.py from docs/api/openapi.yaml.
// DO NOT EDIT BY HAND — regenerate with `make api-gen` after changing the
// spec. The management API registers and validates every route against
// this table (contract testing, p6.api-impl).

package api

// specRoutes is the compiled route table of the OpenAPI contract. Every
// entry must have a handler registered under the same OperationID; the
// conformance test asserts set equality and auth behavior.
var specRoutes = []routeSpec{
"""

def main():
    check = "--check" in sys.argv
    with open(SPEC) as f:
        doc = yaml.safe_load(f)

    rows = []
    for path, item in sorted(doc["paths"].items()):
        for method, op in sorted(item.items()):
            if method in ("parameters",) or method.startswith("x-"):
                continue
            rows.append(
                f'\t{{Method: "{method.upper()}", Path: "{path}", '
                f'OperationID: "{op["operationId"]}", '
                f'Auth: "{op["x-auth"]}", RateLimit: "{op["x-rate-limit"]}"}},'
            )

    body = HEADER + "\n".join(rows) + "\n}\n"
    want = body.encode()

    try:
        have = open(OUT, "rb").read()
    except FileNotFoundError:
        have = None

    if check:
        if have == want:
            print(f"OK: {OUT} up to date with {SPEC} ({len(rows)} routes)")
            return 0
        print(f"STALE: {OUT} does not match {SPEC} — run `make api-gen`")
        return 1

    with open(OUT, "w") as f:
        f.write(body)
    print(f"wrote {OUT}: {len(rows)} routes from {SPEC}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
